export const FALLBACK_CONTENT = {
  // Header
  'header.logo.title': 'Maoz Digital',
  'header.nav.home': 'בית',
  'header.nav.services': 'שירותים',
  'header.nav.contact': 'צור קשר',
  'header.nav.results': 'גלריית תוצאות',
  'header.nav.admin': 'כניסת מנהל',
  'header.cta.start': 'התחל פרויקט',

  // Hero section
  'hero.tagline': 'סטודיו פרימיום לשיווק דיגיטלי',
  'hero.title': 'Maoz Digital',
  'hero.subtitle': 'אסטרטגיה, עיצוב ושיווק שמביאים תוצאות מדויקות',
  'hero.description':
    'אתרים מוקפדים, קמפיינים ממוקדים ומדידה שקופה. אנחנו בונים עבורך נוכחות דיגיטלית רגועה, מדויקת ומניבה – ללא עומס ועם הרבה שיק.',
  'hero.primaryCta': 'גלה את השירותים שלנו',
  'hero.secondaryCta': 'צור קשר עכשיו',
  'hero.stats.leads.value': '10,000+',
  'hero.stats.leads.label': 'לידים שסיפקנו לעסקים',
  'hero.stats.roi.value': '300%',
  'hero.stats.roi.label': 'ממוצע גידול בהחזר ההשקעה',
  'hero.stats.experience.value': '3 שנים',
  'hero.stats.experience.label': 'ניסיון בבניית מותגים ושיווק',
  'hero.stats.availability.value': '24/7',
  'hero.stats.availability.label': 'זמינות וליווי אישי',

  // Services section
  'services.heading': 'שירותים נקיים, תוצאה יוקרתית',
  'services.subheading':
    'מעטפת שיווקית שמתחילה באתר מוקפד, ממשיכה בקמפיינים מלוטשים ומסתיימת בדוחות תמציתיים וברורים.',
  'services.card.tagline': 'Maoz Digital',
  'services.items.web.title': 'בניית אתרי פרימיום + Google Growth',
  'services.items.web.description':
    'עיצוב ופיתוח אתרים אלגנטיים לצד אסטרטגיית Google מדויקת – SEO, Performance Max וקמפיינים מבוססי נתונים.',
  'services.items.web.feature1': 'UX/UI ממוקד המרה',
  'services.items.web.feature2': 'SEO טכני ותוכן חכם',
  'services.items.web.feature3': 'אתרים מהירים ונקיים',
  'services.items.web.feature4': 'קמפייני Google מולטי-ערוצים',
  'services.items.meta.title': 'Meta Luxury Campaigns',
  'services.items.meta.description':
    'קמפיינים בפייסבוק ובאינסטגרם עם קריאייטיב מוקפד, פלחי קהל חכמים ואופטימיזציות רציפות.',
  'services.items.meta.feature1': 'קונספט קריאייטיב מותגי',
  'services.items.meta.feature2': 'מסעות לקוח מדורגים',
  'services.items.meta.feature3': 'אוטומציות ו-CRM',
  'services.items.meta.feature4': 'בדיקות A/B על בסיס נתונים',
  'services.items.tiktok.title': 'TikTok Performance Studio',
  'services.items.tiktok.description':
    'תוכן קצר שמרגיש טבעי בטיקטוק אבל עובד למטרות עסקיות – הפקות מהירות, Spark Ads וניתוח ביצועים.',
  'services.items.tiktok.feature1': 'אסטרטגיית תוכן עדכנית',
  'services.items.tiktok.feature2': 'שיתופי פעולה עם יוצרים',
  'services.items.tiktok.feature3': 'טרנדים והוקים רלוונטיים',
  'services.items.tiktok.feature4': 'מעקב אנליטי מלא',
  'services.items.cta': 'קבעו שיחת התאמה ↗',

  // Gallery section
  'gallery.tagline': 'Meta Results',
  'gallery.title': 'ביצועים מדויקים בקמפיינים ממומנים',
  'gallery.description':
    'אנו מנהלים את קמפייני Meta (פייסבוק ואינסטגרם) בגישה שמרכזת נתונים אמיתיים, חוויית משתמש מדויקת, ותהליכי אופטימיזציה שקטים אך עקביים.',
  'gallery.metrics.reach.title': 'Meta Leads',
  'gallery.metrics.reach.value': '850K+',
  'gallery.metrics.reach.caption': 'הגעה חודשית ממוצעת',
  'gallery.metrics.conversions.title': 'Meta Conversions',
  'gallery.metrics.conversions.value': '15K+',
  'gallery.metrics.conversions.caption': 'המרות ממוקדות בחודש',
  'gallery.metrics.engagements.title': 'Meta Engagements',
  'gallery.metrics.engagements.value': '2.5M+',
  'gallery.metrics.engagements.caption': 'אינטראקציות חודשיות חדשות',
  'gallery.box.title': 'מה זה אומר בפועל?',
  'gallery.box.feature1': 'קמפיינים ממוקדים עם ROAS גבוה',
  'gallery.box.feature2': 'דו"חות שבועיים ברורים וממוקדים',
  'gallery.box.feature3': 'ליווי שוטף ודיוק קהלים בהתאם לנתונים',
  'gallery.button': 'עיינו בתוצאות הקמפיינים ↗',
  'gallery.card.topline.left': 'Meta Ads Manager',
  'gallery.card.topline.separator': '•',
  'gallery.card.topline.right': 'Real Campaign Dashboards',
  'gallery.card.description':
    'תצלומי מסך מתוך הדשבורד של לקוחותינו. נתוני אמת שממחישים את הדיוק ואיכות הקמפיינים שאנו מנהלים.',
  'gallery.card.button': 'פתיחת תצוגה מוגדלת ↗',

  // Rating system section
  'ratings.heading': 'מה הלקוחות שלנו מספרים',
  'ratings.description':
    'ביקורות אמיתיות שמוכיחות שקל לעבוד איתנו ושאנחנו מביאים תוצאות.',
  'ratings.loadingReviews': 'טוען ביקורות...',
  'ratings.errorReviews': 'שגיאה בטעינת הדירוגים',
  'ratings.emptyReviews': 'אין לנו עדיין ביקורות כתובות, נשמח אם תשאירו את הראשונה!',
  'ratings.nextReview': '→',
  'ratings.prevReview': '←',
  'ratings.loadingScores': 'טוען דירוגים...',
  'ratings.errorScores': 'שגיאה בטעינת הדירוגים',
  'ratings.viewOnGoogle': 'צפה בביקורות בגוגל ↗',
  'ratings.leaveReview': 'השאר ביקורת בגוגל ↗',
  'ratings.googleLabel': 'Google Reviews',
  'ratings.totalPrefix': 'מבוסס על',
  'ratings.totalSuffix': 'ביקורות',

  // Contact section
  'contact.heading': 'בואו נשב לקפה דיגיטלי',
  'contact.subheading':
    'ממלאים את הפרטים או פונים אלינו בערוץ שנוח לכם – חוזרים תוך 24 שעות עם כיוון ברור להמשך.',
  'contact.channels.title': 'ערוצי קשר',
  'contact.channels.email': 'omermaoz1998@gmail.com',
  'contact.channels.whatsapp': 'דברו איתנו בוואטסאפ',
  'contact.channels.location': 'ישראל | פרויקטים בינלאומיים',
  'contact.hours.title': 'שעות פעילות',
  'contact.hours.weekdays': 'א-ה: 08:00 - 21:00',
  'contact.hours.friday': 'ו: 08:00 - 19:00',
  'contact.hours.note': 'נשיב גם מחוץ לשעות עם מענה מייל מסודר.',
  'contact.form.nameLabel': 'שם מלא *',
  'contact.form.namePlaceholder': 'הכנס את השם המלא',
  'contact.form.emailLabel': 'אימייל *',
  'contact.form.emailPlaceholder': 'example@email.com',
  'contact.form.phoneLabel': 'טלפון *',
  'contact.form.phonePlaceholder': 'הכנס מספר טלפון',
  'contact.form.companyLabel': 'שם החברה',
  'contact.form.companyPlaceholder': 'שם החברה (אופציונלי)',
  'contact.form.serviceLabel': 'שירות מבוקש *',
  'contact.form.servicePlaceholder': 'בחר שירות',
  'contact.form.budgetLabel': 'תקציב משוער',
  'contact.form.budgetPlaceholder': 'בחר תקציב',
  'contact.form.messageLabel': 'הודעה',
  'contact.form.messagePlaceholder': 'פרט על הפרויקט שלך...',
  'contact.form.submit.whatsapp': 'שלח פנייה דרך WhatsApp',
  'contact.form.submit.mail': 'שלח פנייה דרך Mail',
  'contact.form.submit.sending': 'שולח...',
  'contact.form.success.whatsapp': 'תודה! פתחנו עבורך שיחת WhatsApp. נחזור אליך תוך 24 שעות.',
  'contact.form.success.mail': 'תודה! פתחנו עבורך הודעת מייל. נחזור אליך תוך 24 שעות.',
  'contact.form.error': 'אירעה שגיאה. נסו שוב או פנו אלינו בוואטסאפ.',
  'contact.form.afterHours.title': 'מחוץ לשעות העבודה',
  'contact.form.afterHours.description':
    'כרגע אנחנו מחוץ לשעות הפעילות. השאירו פרטים במייל ונחזור אליכם בהקדם.',
  'contact.form.afterHours.openMail': 'פתח מייל',
  'contact.form.afterHours.cancel': 'ביטול',
  'contact.services.option.web': 'בניית אתרים + שיווק בגוגל',
  'contact.services.option.meta': 'שיווק ממומן במטא (פייסבוק + אינסטגרם)',
  'contact.services.option.tiktok': 'שיווק ממומן בטיקטוק',
  'contact.services.option.bundle': 'שירותים משולבים',
  'contact.services.option.consulting': 'ייעוץ דיגיטלי',
  'contact.budgets.option.1': '₪2,000 - ₪5,000',
  'contact.budgets.option.2': '₪5,000 - ₪10,000',
  'contact.budgets.option.3': '₪10,000 - ₪20,000',
  'contact.budgets.option.4': '₪20,000 - ₪50,000',
  'contact.budgets.option.5': 'מעל ₪50,000',

  // Footer
  'footer.brand.title': 'Maoz Digital',
  'footer.brand.tagline': 'Digital Studio',
  'footer.brand.description': 'סטודיו בוטיק לשיווק דיגיטלי. אתרים נקיים, קמפיינים ממוקדים ונתונים שמדברים בעד עצמם.',
  'footer.services.title': 'השירותים שלנו',
  'footer.services.item1': 'בניית אתרי פרימיום + SEO',
  'footer.services.item2': 'ניהול קמפיינים ב-Google',
  'footer.services.item3': 'Meta Luxury Campaigns',
  'footer.services.item4': 'TikTok Performance Studio',
  'footer.services.item5': 'אסטרטגיה, דאטה ואוטומציות',
  'footer.contact.title': 'צור קשר',
  'footer.contact.email': 'omermaoz1998@gmail.com',
  'footer.contact.whatsapp': 'שלחו הודעה בוואטסאפ',
  'footer.contact.location': 'ישראל | פרויקטים בינלאומיים',
  'footer.copyright': '© {year} Maoz Digital – עומר מעוז. כל הזכויות שמורות.',
} as const;

export type EditableContentKey = keyof typeof FALLBACK_CONTENT;

